---
- hosts: all
  sudo: yes

  roles:
    - ruby

  # Development-specific tasks
  # If they get too large, make them a role as well
  tasks:
# Create database user with name 'bob' and password '12345'
# with all database privileges
# MySQL modules
    - name: Install MySQL
      apt: name={{ item }} state=latest
      with_items:
        - mysql-server
    - name: Run bundle install
      shell: bundle install chdir=/vagrant
